-- ============================================================
-- Vendor Performance & Procurement Cost Analysis
-- KS Textile Shop · Tamil Nadu · INR
-- Author: Vishnukanth Sekar
-- Run against: SQLite (generated by vendor_analysis.py)
--              or any SQL database
-- ============================================================


-- ── QUERY 1: Overall vendor scorecard ────────────────────────────────────
-- Shows key performance metrics for all vendors, ranked by weighted score
SELECT
    v.vendor_name,
    v.location,
    v.category,
    COUNT(p.po_id)                                              AS total_orders,
    SUM(p.order_value_inr)                                      AS total_spend_inr,
    ROUND(AVG(p.actual_lead_days - p.committed_lead_days), 2)   AS avg_lead_variance_days,
    ROUND(AVG(p.received_qty * 1.0 / p.ordered_qty * 100), 2)  AS avg_fill_rate_pct,
    ROUND(AVG(p.return_qty * 1.0 / p.received_qty * 100), 2)   AS avg_return_rate_pct,
    SUM(CASE WHEN p.actual_lead_days <= p.committed_lead_days
             THEN 1 ELSE 0 END)                                 AS on_time_deliveries,
    ROUND(SUM(CASE WHEN p.actual_lead_days <= p.committed_lead_days
                   THEN 1.0 ELSE 0 END) / COUNT(*) * 100, 1)   AS on_time_pct,
    SUM(p.emergency_purchase_inr)                               AS total_emergency_cost_inr
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name, v.location, v.category
ORDER BY avg_lead_variance_days ASC;


-- ── QUERY 2: Monthly emergency procurement cost trend ────────────────────
-- Identifies which months had the highest emergency spending (INR)
SELECT
    p.month,
    v.vendor_name,
    SUM(p.emergency_purchase_inr)                               AS monthly_emergency_inr,
    ROUND(AVG(p.actual_lead_days - p.committed_lead_days), 1)  AS avg_lead_delay
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
WHERE p.emergency_purchase_inr > 0
GROUP BY p.month, v.vendor_id, v.vendor_name
ORDER BY monthly_emergency_inr DESC;


-- ── QUERY 3: Slow vendor identification ──────────────────────────────────
-- Flags vendors whose average lead time exceeds the 5-day commitment
SELECT
    v.vendor_name,
    ROUND(AVG(p.actual_lead_days), 1)                          AS avg_actual_days,
    p.committed_lead_days,
    ROUND(AVG(p.actual_lead_days) - p.committed_lead_days, 1)  AS avg_delay_days,
    COUNT(CASE WHEN p.actual_lead_days > p.committed_lead_days
               THEN 1 END)                                      AS late_deliveries,
    COUNT(p.po_id)                                              AS total_orders,
    ROUND(COUNT(CASE WHEN p.actual_lead_days > p.committed_lead_days
                     THEN 1 END) * 100.0 / COUNT(p.po_id), 1)  AS late_delivery_pct
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name, p.committed_lead_days
HAVING avg_delay_days > 0
ORDER BY avg_delay_days DESC;


-- ── QUERY 4: Fill rate and quality breakdown ──────────────────────────────
-- Shows which vendors are short-shipping and returning defective goods
SELECT
    v.vendor_name,
    SUM(p.ordered_qty)                                          AS total_ordered,
    SUM(p.received_qty)                                         AS total_received,
    SUM(p.ordered_qty) - SUM(p.received_qty)                   AS total_short_shipped,
    SUM(p.return_qty)                                           AS total_returns,
    ROUND(SUM(p.received_qty) * 100.0 / SUM(p.ordered_qty), 2) AS fill_rate_pct,
    ROUND(SUM(p.return_qty) * 100.0 / SUM(p.received_qty), 2)  AS return_rate_pct,
    SUM(p.order_value_inr)                                      AS total_spend_inr,
    ROUND(SUM(p.return_qty) * SUM(p.order_value_inr) * 1.0
          / SUM(p.received_qty), 0)                             AS estimated_return_cost_inr
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name
ORDER BY fill_rate_pct ASC;


-- ── QUERY 5: Total avoidable cost summary ────────────────────────────────
-- Quantifies the total financial impact of underperforming vendors (INR)
SELECT
    v.vendor_name,
    SUM(p.emergency_purchase_inr)                               AS emergency_cost_inr,
    ROUND(SUM(p.return_qty) * SUM(p.order_value_inr) * 1.0
          / NULLIF(SUM(p.received_qty),0), 0)                   AS estimated_return_cost_inr,
    SUM(p.emergency_purchase_inr)
        + ROUND(SUM(p.return_qty) * SUM(p.order_value_inr) * 1.0
                / NULLIF(SUM(p.received_qty),0), 0)             AS total_avoidable_cost_inr
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name
ORDER BY total_avoidable_cost_inr DESC;


-- ── QUERY 6: Reorder recommendation — top 2 vendors for reallocation ─────
SELECT
    v.vendor_name,
    v.category,
    ROUND(AVG(p.received_qty * 1.0 / p.ordered_qty * 100), 1)  AS fill_rate_pct,
    ROUND(AVG(p.actual_lead_days - p.committed_lead_days), 1)   AS avg_delay,
    SUM(p.emergency_purchase_inr)                               AS emergency_cost_inr,
    CASE
        WHEN AVG(p.received_qty * 1.0 / p.ordered_qty * 100) >= 99
             AND AVG(p.actual_lead_days - p.committed_lead_days) <= 0
        THEN 'INCREASE ALLOCATION'
        WHEN SUM(p.emergency_purchase_inr) > 50000
             OR AVG(p.actual_lead_days - p.committed_lead_days) > 5
        THEN 'REDUCE ALLOCATION'
        ELSE 'MAINTAIN'
    END AS recommendation
FROM purchase_orders p
JOIN vendor_info v ON p.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name, v.category
ORDER BY fill_rate_pct DESC;
